id: I2F3454EC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T02:34:48+00:00'
last_modified: '2022-06-08T13:50:07.040809+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21963
  title: བཀའ་བརྒྱུད་མགུར་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    ACCF:
      image_group_id: I3013
      title: ''
      total_pages: 512
      order: 1
      base_file: ACCF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
