id: P010469
initial_creation_type: ocr
source_metadata:
  id: bdr:W21963
  title: བཀའ་བརྒྱུད་མགུར་མཚོ
  author: ''
  volumes:
    117b009012ae458bb584a42350ff04a9:
      image_group_id: I3013
      title: ''
      volume_number: 1
      total_pages: 512
