id: P010469
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 20:51:28.759177
source_metadata:
  id: bdr:W21963
  title: བཀའ་བརྒྱུད་མགུར་མཚོ
  author: ''
  volumes:
    117b009012ae458bb584a42350ff04a9:
      image_group_id: I3013
      title: ''
      volume_number: 1
      total_pages: 512
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
